### ISSUE TITLE
Rework the hardware status (disks, raid controller etc.) display in the web UI

### ISSUE THREAD

**Issue by subu1962** [digimer/striker#14]
Currently in the web UI, each disk status is shown as a block with complete details. It would be better to just give the drive state and may be temperature of all the drives in a table and have links that take you to the display giving you all the pertinent details such as error counts etc.

**Comment by digimer** [comment]
With the new Scan Core coming online, the section where you can see and manage the storage needs to be revamped to add information on other sensors from the nodes. We also plan to switch the LSi-based storage management from using MegaCli to StorCli. These steps will require a fair bit of work, and compacting the display will be important. So I think this is an excellent idea and we will implement it in the next full release.

Thanks for the suggestion!

**Comment by digimer** [comment]
Closing this as we're likely not going to make this change in v2.0, though this comment will inform Striker v3.0 development which is about to start.
