### ISSUE TITLE
The color scheme on the web UI could use a revamp

### ISSUE THREAD

**Issue by subu1962** [digimer/striker#16]
Currently various colors such as "purple", "blue" and "green" are used in the various web pages. It's not always clear where the links are (for ex: turn the LED on is a link that performs an action) ....

It looks like the "purple" colored words/phrases are links. May be making them "bold" to stand out might be enough.

**Comment by digimer** [comment]
We're actually getting a total revamp of our website, logos and so on. So we'll be revamping Striker's default skin to match as part of the process. This may or may not be done for the next release, but it certainly is in the works.

**Comment by digimer** [comment]
Closing this as the current skin will be, more or less, what will be used for Striker v2. If anyone wants to provide tweaks to the CSS though, I'll be happy to test/integrate.
