### ISSUE TITLE
Node Manifest installation stalls on creating partition, attempts to create 0GB drive

### ISSUE THREAD

**Issue by nummysquee** [digimer/striker#19]
The Stage 2 Node install from a single striker stalls if a VM partition is already created. 

Drive layout prior to running the manifest:
> Number  Start   End     Size    Type      File system     Flags
> 1      1049kB  538MB   537MB   primary   ext4            boot
> 2      538MB   43.5GB  42.9GB  primary   ext4
> 3      43.5GB  47.8GB  4295MB  primary   linux-swap(v1)
> 4      47.8GB  1497GB  1449GB  extended                  lba
> 5      47.8GB  1497GB  1449GB  logical

striker.log output:

> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [Model: FTS PRAID EP420i (scsi)]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [Disk /dev/sda: 1394GiB]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [Sector size (logical/physical): 512B/512B]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [Partition Table: msdos]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: []
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [Number Start End Size Type File system Flags]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [0.00GiB 0.00GiB 0.00GiB Free Space]
> 13:09:03 AN::InstallManifest.pm 7686; start: [0.00], end: [0.00], size: [0.00]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [1 0.00GiB 0.50GiB 0.50GiB primary ext4 boot]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [2 0.50GiB 40.5GiB 40.0GiB primary ext4]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [3 40.5GiB 44.5GiB 4.00GiB primary linux-swap(v1)]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [4 44.5GiB 1394GiB 1350GiB extended lba]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: [5 44.5GiB 1394GiB 1350GiB logical]
> 13:09:03 AN::InstallManifest.pm 7680; node: [10.20.10.201], disk: [sda], return: []
> 13:09:03 AN::InstallManifest.pm 7691; node: [10.20.10.201], disk: [sda], start: [0.00], end: [0.00].
> 13:09:03 AN::InstallManifest.pm 7712; node: [10.20.10.201], disk: [sda], type: [extended], partition_size: [all]
> 13:09:03 AN::InstallManifest.pm 7739; snode: [10.20.10.201], disk: [sda], type: [extended], start: [0.00 GiB], end: [0.00 GiB]
> 13:09:03 AN::InstallManifest.pm 7746; shell_call: [parted -a opt /dev/sda mkpart extended 0.00GiB 100%]

Steps to recreate:

Initialize Anvil from dashboard, already have a partition for VMs created. 

Removing the partitions causes the installer to create them from scratch, and circumvents the issue.

**Comment by digimer** [comment]
This should be fixed in 68875a70864702aae469934f5d9e396eaaf4607f. Please re-open if issue remains.
